ensure ssh keys are deployed via github actions

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -70,30 +70,32 @@ jobs:
     - name: Ensure SSM Agent is Running
       env:
        INSTANCE_ID: ${{ steps.extract_id.outputs.INSTANCE_ID }}
-      run: |
-        # Polling for the SSM agent to be running on the EC2 instance
-        instance_id="$INSTANCE_ID"  # Replace with your instance ID
-        echo "$INSTANCE_ID"
-        max_retries=30
-        retry_count=0
-        ssm_status=""
+      run: sleep 60
+      #run: |
+      #  # Polling for the SSM agent to be running on the EC2 instance
+      #  instance_id="$INSTANCE_ID"  # Replace with your instance ID
+      #  echo "$INSTANCE_ID"
+      #  max_retries=30
+      #  retry_count=0
+      #  ssm_status=""
 
-        while [ "$retry_count" -lt "$max_retries" ]; do
-          ssm_status=$(aws ec2 describe-instance-status --instance-ids "$INSTANCE_ID" --query "InstanceStatuses[0].InstanceStatus.Status" --output text)
-          if [ "$ssm_status" == "ok" ]; then
-            echo "SSM Agent is running."
-            break
-          else
-            echo "SSM Agent is not running. Retrying..."
-            sleep 20
-            ((retry_count++))
-          fi
-        done
+      #  while [ "$retry_count" -lt "$max_retries" ]; do
+      #    ssm_status=$(aws ec2 describe-instance-status --instance-ids "$INSTANCE_ID" --query "InstanceStatuses[0].InstanceStatus.Status" --output text)
+      #    if [ "$ssm_status" == "ok" ]; then
+      #      echo "$INSANCE_ID"
+      #      echo "SSM Agent is running."
+      #      break
+      #    else
+      #      echo "SSM Agent is not running. Retrying..."
+      #      sleep 60
+      #      ((retry_count++))
+      #    fi
+      #  done
 
-        if [ "$retry_count" -ge "$max_retries" ]; then
-          echo "SSM Agent did not start in time. Exiting."
-          exit 1
-        fi
+      #  if [ "$retry_count" -ge "$max_retries" ]; then
+      #    echo "SSM Agent did not start in time. Exiting."
+      #    exit 1
+      #  fi
 
     - name: Send SSH Key to EC2
       env:
